### ISSUE TITLE
TypeError when running tests

### ISSUE THREAD

**Issue by StormChild** [mainfraame/cucumber-jest#24]
After the default setup using cucumber-jest as per the documentation I get the following error:

``` 
TypeError: Cannot destructure property 'instrument' of 'undefined' as it is undefined.

      at Object.getCacheKey (node_modules/cucumber-jest/src/index.ts:11:54)
      at ScriptTransformer._getCacheKey (node_modules/@jest/transform/build/ScriptTransformer.js:281:41)
      at ScriptTransformer._getFileCachePath (node_modules/@jest/transform/build/ScriptTransformer.js:352:27)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:595:32)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:765:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:822:19)
```

**Comment by kogratte** [comment]
So am I. Any idea?

**Comment by lukasreinfurt** [comment]
I've been running into the same issue. I tried different Jest version (26, 27, 28) but no luck so far.

**Comment by Narmical** [comment]
I am also having this issue. Any plans to update this package to work with jest 29?
