### ISSUE TITLE
Getting an issue with DataTable

### ISSUE THREAD

**Issue by pdashford** [mainfraame/cucumber-jest#5]
Hi, I have the following

``` 
Scenario: I add products
    Given I add the following products
      | level | product          | supplier       |       
      | 01     | My product   | My supplier |
```

```
Given('I add the following products', async (table) => {
  for (const row of table) {
```

When running the test I receive the following error

``` TypeError: definition.pattern.exec is not a function```

```
at exec (node_modules/cucumber-jest/src/utils/parseFeature.ts:211:43)
          at Array.reduce (<anonymous>)
      at reduce (node_modules/cucumber-jest/src/utils/parseFeature.ts:190:18)
      at bindGherkinSteps (node_modules/cucumber-jest/src/utils/parseFeature.ts:369:20)
          at Array.map (<anonymous>)
      at map (node_modules/cucumber-jest/src/utils/parseFeature.ts:367:24)
      at parseGherkinSuites (node_modules/cucumber-jest/src/utils/parseFeature.ts:397:18)
```

And on the console it points to a line that is not relevant to that test condition.

Thanks

**Comment by pdashford** [comment]
So I've found the issue, in `parseFeature.ts` line `210` you are expecting that the title is always going to be a `regEx` pattern, hence changing the test to be 

```
Given(/^I add the following products$/, async (table) => {
```

Would probably be worth checking if the title is a standard string

**Comment by mainfraame** [comment]
@pdashford i recently merged a PR to fix this issue from a contributor. I’ll run a build later today with that fix in it.

**Comment by mainfraame** [comment]
@pdashford I did the release today with this fix. Please let me know if you're still having this issue. v0.1.1
